name: Cron-staging
on:
  schedule:
    - cron: "0 4 * * *"
jobs:
  experiment-integration:
    if: github.repository_owner == 'Qiskit-Extensions'
    name: ibm-experiment-integration
    runs-on: macOS-latest
    env:
      QISKIT_IBM_STAGING_API_TOKEN: ${{ secrets.QISKIT_IBM_STAGING_API_TOKEN }}
      QISKIT_IBM_STAGING_API_URL: ${{ secrets.QISKIT_IBM_STAGING_API_URL }}
      QISKIT_IBM_STAGING_HGP: ${{ secrets.QISKIT_IBM_STAGING_HGP }}
      QISKIT_IBM_STAGING_BACKEND: ${{ secrets.QISKIT_IBM_STAGING_BACKEND }}
      QISKIT_IBM_USE_STAGING_CREDENTIALS: True
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Deps
        run: python -m pip install -U tox setuptools virtualenv wheel
      - name: Run Server Integration Tests
        run: tox -epy38 -- -n test/service/test_experiment_server_integration.py
      - name: Run Experiment Data Integration Tests
        run: tox -epy38 -- -n test/service/test_experiment_data_integration.py
